// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN99jkYqV9c77HKBQ_Pk6GohxfwtiAEOI',
    appId: '1:167384711766:web:946042ac590fa6a609b1f7',
    messagingSenderId: '167384711766',
    projectId: 'ewishes-e3caa',
    authDomain: 'ewishes-e3caa.firebaseapp.com',
    storageBucket: 'ewishes-e3caa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiokJepFgvVYiTZqJ8w3m-SP9ROpFG_Qs',
    appId: '1:167384711766:android:b112ed4bc176039a09b1f7',
    messagingSenderId: '167384711766',
    projectId: 'ewishes-e3caa',
    storageBucket: 'ewishes-e3caa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcb6Def3HaDc4bRfC3hq1lHxeaLy6dThY',
    appId: '1:167384711766:ios:a5ac8305fcf9100409b1f7',
    messagingSenderId: '167384711766',
    projectId: 'ewishes-e3caa',
    storageBucket: 'ewishes-e3caa.appspot.com',
    iosBundleId: 'com.example.topsProjectGreet',
  );
}
